services:
  ptc:
    image: ptc:latest
    container_name: contact_planning
    # mem_limit: 16g
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256-color
      - MOSEKLM_LICENSE_FILE=/root/workspace/mosek
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - ./:/root/workspace/
      - ${HOME}/mosek:/root/workspace/mosek
    tty: true
    stdin_open: true
    network_mode: "host"
    privileged: true
    ulimits:
      rtprio: 70
      rttime: -1
      memlock: 8428281856
    devices:
      - "/dev:/dev"
    command: /bin/bash
